//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng..
        /// </summary>
        public static string AccountNotCorrect {
            get {
                return ResourceManager.GetString("AccountNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối tới cơ sở dữ liệu..
        /// </summary>
        public static string ConnectDbException {
            get {
                return ResourceManager.GetString("ConnectDbException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khách hàng.
        /// </summary>
        public static string CustomerClassname {
            get {
                return ResourceManager.GetString("CustomerClassname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được phép để trống..
        /// </summary>
        public static string CustomerCodeNotEmpty {
            get {
                return ResourceManager.GetString("CustomerCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string DateGreatThanToday {
            get {
                return ResourceManager.GetString("DateGreatThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được để trống..
        /// </summary>
        public static string DepartmentNotEmpty {
            get {
                return ResourceManager.GetString("DepartmentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã {0} &lt;{1}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại trong hệ thống..
        /// </summary>
        public static string DuplicateCustomerCode {
            get {
                return ResourceManager.GetString("DuplicateCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhân viên.
        /// </summary>
        public static string EmployeeClassname {
            get {
                return ResourceManager.GetString("EmployeeClassname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File nhập khẩu không được để trống..
        /// </summary>
        public static string FileImportNotEmpty {
            get {
                return ResourceManager.GetString("FileImportNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File nhập khẩu không đúng định dạng..
        /// </summary>
        public static string FileImportNotValid {
            get {
                return ResourceManager.GetString("FileImportNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được phép để trống..
        /// </summary>
        public static string FullNameNotEmpty {
            get {
                return ResourceManager.GetString("FullNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công..
        /// </summary>
        public static string InsertFailure {
            get {
                return ResourceManager.GetString("InsertFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet không được để trống..
        /// </summary>
        public static string IsExit_Worksheet {
            get {
                return ResourceManager.GetString("IsExit_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số cột nhập khẩu không đúng so với file mẫu..
        /// </summary>
        public static string IsValidTotalColumns {
            get {
                return ResourceManager.GetString("IsValidTotalColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền phải lớn hơn không..
        /// </summary>
        public static string MoneyGreatThanZezo {
            get {
                return ResourceManager.GetString("MoneyGreatThanZezo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cột {0} không giống với file mẫu..
        /// </summary>
        public static string NotEqualColumnsFile {
            get {
                return ResourceManager.GetString("NotEqualColumnsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} này không tồn tại trong hệ thống..
        /// </summary>
        public static string NotExitSystem {
            get {
                return ResourceManager.GetString("NotExitSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách {0}.
        /// </summary>
        public static string ObjectList {
            get {
                return ResourceManager.GetString("ObjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể truy cập!.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công..
        /// </summary>
        public static string UpdateFailure {
            get {
                return ResourceManager.GetString("UpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi vui lòng liên hệ MISA để được tư vấn..
        /// </summary>
        public static string UserMessage {
            get {
                return ResourceManager.GetString("UserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lệ..
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nghỉ việc.
        /// </summary>
        public static string WorkStatus_Stopped {
            get {
                return ResourceManager.GetString("WorkStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc.
        /// </summary>
        public static string WorkStatus_Working {
            get {
                return ResourceManager.GetString("WorkStatus_Working", resourceCulture);
            }
        }
    }
}
